### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by yanghyunjun** [ovsoinc/yacdn.org#235]
fetch("
https://yacdn.org/proxy/http://openapi.data.go.kr/openapi/service/rest/Covid19/getCovid19NatInfStateJson?serviceKey=BgwP4pyTado5recbSerXHA93SWAy%2B1AExNGuxbCIHpP4xIhxz%2BJTkNiXkY36oYhzG1L9C6G976iuiX6yPM1oZw%3D%3D&_type=json&startCreateDt=20200620 ")
"Internal Server Error" appears when fetching the url,
Is there an error due to the large amount of data on the api?
The other url that brings in a small amount of data works.
Is it impossible to get around 200 pieces of data?

**Comment by jimmywarting** [comment]
I had a problem loading one small image also
the image couldn't load if i don't have the search params included `?id=`.

here is the image:
http://shop.origum.se/images?id=1101858140

I guess that interfere with internal and external search params.
Guess a better alternative would be to just do: `?url=${urlEncoded}&maxAge=3200` it provides with more internal features that can be expanded upon such as:
```
https://yacdn.org/proxy/
?url=x
&width=x
&maxAge=
&crop=
&format=auto|best|webp|jpeg
```
...and more

**Comment by joebone** [comment]
Just another example of 500 here to help reproduce, assuming its the same issue..
https://yacdn.org/serve/https://api.github.com/repos/fmendels/TailBlazer/commits?sha=color_logfile&since=2020-05-13

I tried uriencoding the whole thing, but that fails spectacularly before even getting to the problematic querystring-enabled ones..
https://yacdn.org/serve/https%3A%2F%2Fapi.github.com%2Frepos%2FRolandPheasant%2FTailBlazer%2Fbranches

**Comment by super3** [comment]
Just shut down the service.
